name: workflow_exemplo

on: 
  push:

env:
  VARIAVEL_1: Felipe Yudi
  VARIAVEL_2: São Paulo

jobs:
  
  checkout_code:
    name: Faz Checkout de codigo
    runs-on: ubuntu-latest
    env:
      VARIAVEL_JOB: 33
    
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3.3.0
      
    - name: Upload a Build Artifact
      uses: actions/upload-srtifact@3.1.2
      with:
        name: ${{vars.NOME}}
        path: .
        

    
